apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcd-bg-demo-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kcd-bg-demo
  template:
    metadata:
      labels:
        app: kcd-bg-demo
        color: blue
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: kcd-bg-demo-blue
          image: ghcr.io/stephaniehhnbrg/kcd-demo:blue
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "8185"
          ports:
          - name: http
            containerPort: 8185
          startupProbe:
            tcpSocket:
              port: 8185
            initialDelaySeconds: 20
            periodSeconds: 5