apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcd-canary-demo-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kcd-canary-demo
      version: v2
  template:
    metadata:
      labels:
        app: kcd-canary-demo
        version: v2
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: kcd-canary-demo
          image: ghcr.io/stephaniehhnbrg/kcd-demo:v2
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8186"
          ports:
            - name: http
              containerPort: 8186
          startupProbe:
            tcpSocket:
              port: 8186
            initialDelaySeconds: 30
            periodSeconds: 5