{{- if eq .Values.color "blue" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  release-name: {{ .Values.app.name }}-{{ .Values.color }}
spec:
  selector:
    app: {{ .Values.app.name }}
    color: {{ .Values.color }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
{{- end }}

